### ISSUE TITLE
App crashes when Gym Locations are deleted

### ISSUE THREAD

**Issue by Yongbeom-Kim** [Yongbeom-Kim/pe#3]
When the json object identified by `"nusGymsLocations"` is deleted, the app is unable to open with a `NullPointerException`.

I.e. with the JSON file:

```json
{
  "foods" : [ ],
  "calorieTarget" : {
    "value" : "2000"
  },
  "user" : {
    "height" : {
      "value" : "0"
    },
    "weight" : {
      "value" : "0"
    },
    "idealWeight" : {
      "value" : "0"
    },
    "gender" : {
      "value" : "M"
    },
    "age" : {
      "value" : "0"
    },
    "bmi" : {
      "value" : "NaN",
      "height" : {
        "value" : "0"
      },
      "weight" : {
        "value" : "0"
      }
    }
  }
}
```

The app fails to open with the error log:

```sh
PS C:\Users\Dernbu\Downloads\CS2103 PE\files-for-pe\New folder> java -jar .\[CS2103T-T17-2][NutriGoals].jar
Nov 11, 2022 4:51:48 PM seedu.nutrigoals.MainApp init
INFO: =============================[ Initializing NutriGoals ]===========================
Nov 11, 2022 4:51:48 PM seedu.nutrigoals.MainApp initConfig
INFO: Using config file : config.json
Nov 11, 2022 4:51:48 PM seedu.nutrigoals.MainApp initPrefs
INFO: Using prefs file : preferences.json
Nov 11, 2022 4:51:48 PM seedu.nutrigoals.commons.core.LogsCenter init
INFO: currentLogLevel: INFO
Exception in Application init method
Exception in thread "main" java.lang.RuntimeException: Exception in Application init method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at seedu.nutrigoals.model.NutriGoals.setNusGymsLocations(NutriGoals.java:144)
        at seedu.nutrigoals.storage.JsonSerializableNutriGoals.toModelType(JsonSerializableNutriGoals.java:67)
        at seedu.nutrigoals.storage.JsonNutriGoalsStorage.readNutriGoals(JsonNutriGoalsStorage.java:55)
        at seedu.nutrigoals.storage.StorageManager.readNutriGoals(StorageManager.java:64)
        at seedu.nutrigoals.storage.StorageManager.readNutriGoals(StorageManager.java:58)
        at seedu.nutrigoals.MainApp.initModelManager(MainApp.java:80)
        at seedu.nutrigoals.MainApp.init(MainApp.java:64)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
        ... 2 more
```
In fact, any random characters in the `nusGymsLocations` key will cause the application to crash

```json
{
  "foods" : [ ],
  "nusGysdlkfjmsLocations" : [ {
    "name" : "MPSH",
...
```
causes a similar exception.

Considered a High severity bug because any user could accidentally type characters into the relevant line, but the app becomes unrecoverable afterwards.

**Comment by nus-pe-script** [comment]
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
We acknowledge this bug, but we feel that this should be considered as a Medium bug instead, since not all users will want to edit data through the json file. In fact in our UG we have stated that new users are discouraged from editing the json file and hence it would not be likely that users encounter this issue in their daily use.

# Items for the Tester to Verify

## :question: Issue severity

Team chose [`severity.Medium`]
Originally [`severity.High`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------
